defmodule AshStudioDemo.Repo.Migrations.RenamedOrdinalToNumber do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:tunez_tracks), :ordinal, to: :number
  end

  def down do
    rename table(:tunez_tracks), :number, to: :ordinal
  end
end
