defmodule AshStudioDemo.Repo.Migrations.AddOrdinalToTunezTracks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tunez_tracks) do
      add :ordinal, :bigint
    end
  end

  def down do
    alter table(:tunez_tracks) do
      remove :ordinal
    end
  end
end
