defmodule AshStudioDemo.Repo.Migrations.AlbumsAddOptionalCreatedBy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tunez_albums) do
      add :created_by_id,
          references(:users,
            column: :id,
            name: "tunez_albums_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:tunez_albums, "tunez_albums_created_by_id_fkey")

    alter table(:tunez_albums) do
      remove :created_by_id
    end
  end
end
